apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bj7skuu0w-python
  janus-idp.io/tekton: bj7skuu0w-python
  backstage.io/kubernetes-id: bj7skuu0w-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bj7skuu0w-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
