apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bj7skuu0w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bj7skuu0w-python 
  name: bj7skuu0w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bj7skuu0w-python 
